apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apexon-final-app
  name: springboot-v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apexon-final-app
  template:
    metadata:
      labels:
        app: apexon-final-app
    spec:
      containers:
        - image: bogomolapach/apexon-final-app
          imagePullPolicy: Always
          name: apexon-final-app
          ports:
            - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: apexon-final-app
  name: springboot-v1
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: apexon-final-app
  sessionAffinity: None
  type: LoadBalancer
