spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:35.173.211.216}:32699/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
    out-of-order: true
  kafka:
    bootstrap-servers: 3.231.53.51:9092
    consumer:
      group-id: myGroupId

server:
  port: 8090

logging:
  level:
    org:
      springframework:
        web: DEBUG
