spring:
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    baseline-on-migrate: true
    out-of-order: true

server:
  port: 8090

logging:
  level:
    org:
      springframework:
        web: DEBUG
